#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App5.Resource", IsApplication=true)]

namespace App5
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int animation = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int back_image = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int exit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int laser = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int logo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int loop = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int main_menu = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int mini = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int pic = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int play_now = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int retry = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int rock_shoot = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int rocket = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int rocket_small = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int settings = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int style = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int style2 = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050016
			public const int StartGame = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int about_btn = 2131034136;
			
			// aapt resource value: 0x7f05000b
			public const int back = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int button = 2131034117;
			
			// aapt resource value: 0x7f050017
			public const int button2 = 2131034135;
			
			// aapt resource value: 0x7f050007
			public const int button5 = 2131034119;
			
			// aapt resource value: 0x7f050013
			public const int enemy_life = 2131034131;
			
			// aapt resource value: 0x7f050019
			public const int exit_btn = 2131034137;
			
			// aapt resource value: 0x7f05000a
			public const int hsv = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int imageView = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int imageView2 = 2131034116;
			
			// aapt resource value: 0x7f05000c
			public const int imageViewa1 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int imageViewa2 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int imageViewa3 = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int laser = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int mbll = 2131034121;
			
			// aapt resource value: 0x7f05000f
			public const int mini = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int rocket = 2131034129;
			
			// aapt resource value: 0x7f050008
			public const int score = 2131034120;
			
			// aapt resource value: 0x7f050012
			public const int shoot = 2131034130;
			
			// aapt resource value: 0x7f050015
			public const int textView = 2131034133;
			
			// aapt resource value: 0x7f050006
			public const int textView2 = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int textView3 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int textView4 = 2131034114;
			
			// aapt resource value: 0x7f050014
			public const int user_life = 2131034132;
			
			// aapt resource value: 0x7f050000
			public const int wv = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_game_over = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int game = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
