#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App5.Resource", IsApplication=true)]

namespace App5
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int animation = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back_image = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int exit = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int laser = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int loop = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int main_menu = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int mini = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int pic = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int play_now = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int retry = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int rock_shoot = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int rocket = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int rocket_small = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int settings = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int style = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int style2 = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060016
			public const int StartGame = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int about_btn = 2131099672;
			
			// aapt resource value: 0x7f06000b
			public const int back = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int button = 2131099653;
			
			// aapt resource value: 0x7f060017
			public const int button2 = 2131099671;
			
			// aapt resource value: 0x7f060007
			public const int button5 = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int enemy_life = 2131099667;
			
			// aapt resource value: 0x7f060019
			public const int exit_btn = 2131099673;
			
			// aapt resource value: 0x7f06000a
			public const int hsv = 2131099658;
			
			// aapt resource value: 0x7f060003
			public const int imageView = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int imageView2 = 2131099652;
			
			// aapt resource value: 0x7f06000c
			public const int imageViewa1 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int imageViewa2 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int imageViewa3 = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int laser = 2131099664;
			
			// aapt resource value: 0x7f060009
			public const int mbll = 2131099657;
			
			// aapt resource value: 0x7f06000f
			public const int mini = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int rocket = 2131099665;
			
			// aapt resource value: 0x7f060008
			public const int score = 2131099656;
			
			// aapt resource value: 0x7f060012
			public const int shoot = 2131099666;
			
			// aapt resource value: 0x7f060015
			public const int textView = 2131099669;
			
			// aapt resource value: 0x7f060006
			public const int textView2 = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int textView3 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int textView4 = 2131099650;
			
			// aapt resource value: 0x7f060014
			public const int user_life = 2131099668;
			
			// aapt resource value: 0x7f060000
			public const int wv = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_game_over = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int game = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int laser = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
