#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App5.Resource", IsApplication=true)]

namespace App5
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int animation = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int back_image = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int exit = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int laser = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logo = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int loop = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int main_menu = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int mini = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int more = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int pic = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int play_now = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int retry = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int rock_shoot = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int rocket = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int rocket_small = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int settings = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int shoot = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int style = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int style2 = 2130837525;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001b
			public const int StartGame = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int about_btn = 2131165213;
			
			// aapt resource value: 0x7f070007
			public const int back = 2131165191;
			
			// aapt resource value: 0x7f07001c
			public const int button2 = 2131165212;
			
			// aapt resource value: 0x7f070015
			public const int dy = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int el = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int enemy_life = 2131165202;
			
			// aapt resource value: 0x7f07001e
			public const int exit_btn = 2131165214;
			
			// aapt resource value: 0x7f070006
			public const int hsv = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int imageViaeawa3 = 2131165196;
			
			// aapt resource value: 0x7f070003
			public const int imageView = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int imageView2 = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int imageViewa1 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int imageViewa2 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int imageViewa3 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int imageaViewa3 = 2131165195;
			
			// aapt resource value: 0x7f07000f
			public const int laser = 2131165199;
			
			// aapt resource value: 0x7f070021
			public const int level = 2131165217;
			
			// aapt resource value: 0x7f07001f
			public const int linearLayout1 = 2131165215;
			
			// aapt resource value: 0x7f070019
			public const int main = 2131165209;
			
			// aapt resource value: 0x7f070005
			public const int mbll = 2131165189;
			
			// aapt resource value: 0x7f07000e
			public const int mini = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int more = 2131165197;
			
			// aapt resource value: 0x7f070022
			public const int one = 2131165218;
			
			// aapt resource value: 0x7f070017
			public const int retry = 2131165207;
			
			// aapt resource value: 0x7f070010
			public const int rocket = 2131165200;
			
			// aapt resource value: 0x7f070016
			public const int score = 2131165206;
			
			// aapt resource value: 0x7f070011
			public const int shoot = 2131165201;
			
			// aapt resource value: 0x7f07001a
			public const int textView = 2131165210;
			
			// aapt resource value: 0x7f070020
			public const int textView1 = 2131165216;
			
			// aapt resource value: 0x7f070018
			public const int textView2 = 2131165208;
			
			// aapt resource value: 0x7f070001
			public const int textView3 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int textView4 = 2131165186;
			
			// aapt resource value: 0x7f070024
			public const int three = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int two = 2131165219;
			
			// aapt resource value: 0x7f070014
			public const int user_life = 2131165204;
			
			// aapt resource value: 0x7f070000
			public const int wv = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int game = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int GameOver = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int settings = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int popup = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int backsound = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int blast = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int laser = 2130968578;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
